# Generated by Django 3.0.5 on 2022-03-20 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotator_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpool',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_modelpools', to='annotator_api.Project'),
        ),
        migrations.AlterField(
            model_name='modelpool',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_modelpools', to=settings.AUTH_USER_MODEL),
        ),
    ]
