# Generated by Django 3.0.5 on 2022-04-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator_api', '0002_auto_20220320_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpool',
            name='pool_models',
            field=models.ManyToManyField(blank=True, related_name='pool_models', to='annotator_api.AnnotationModel'),
        ),
    ]
